### ISSUE TITLE
[no-undef]: consider regression

### ISSUE THREAD

**Issue by guilhermetod** [iamturns/eslint-config-airbnb-typescript#144]
Hey, I just upgraded to v11 and got a lot of 'no-undef' errors in my TypeScript files. I went to investigate what happened and realized that the lines that disabled the 'no-undef' rule were removed in #129.

I figured that it's because [typescript-eslint's parser](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/parser/README.md#parseroptionslib) now allows users to specify "libs" available in the global scope, which may have lead to the conclusion this would fix the no-undef duplication error.

However, it doesn't allow users to specify external type packages. So if a user has any packages that declare global variables, you'll still get no-undef rules (e.g. .spec files).

I decided not to PR because I think this should be evaluated by the team before, but I can definetly help if you guys agree.

**Comment by Zamiell** [comment]
I just came across this bug myself; thanks guilhermetod for bringing it up. I was very surprised that this config shipped with the `no-undef` rule on, since it seems to make no sense in conjunction with TypeScript (at least if you are using TypeScript's `strict` mode anyway, which I presume most people use).

In my use-case, I am using the somewhat-popular [TypeScriptToLua](https://typescripttolua.github.io/docs/getting-started/) transpiler, which uses type declarations to imply global variables. So I immediately had to turn off the `no-undef` rule.

**Comment by iamturns** [comment]
Thanks for this reporting this. Removing `no-undef` was unintentional. Sorry about that. This rule has been restored, along with some other rules already checked by the TypeScript compiler. Cheers!
