### ISSUE TITLE
Parser is a dependency but eslint-plugin is a peer dependency

### ISSUE THREAD

**Issue by Methuselah96** [iamturns/eslint-config-airbnb-typescript#158]
Is there a reason why `@typescript-eslint/eslint-plugin` is a peer dependency, but `@typescript-eslint/parser` is a dependency? I'd like for them both to be peer dependencies so that I can use matching versions.

**Comment by leethree** [comment]
agree. also `@typescript-eslint/parser` shouldn't be pinned to a specific version (as I commented on https://github.com/iamturns/eslint-config-airbnb-typescript/pull/153#issuecomment-724618156). otherwise users won't be able to match the version between parser and plugin.

**Comment by Djaler** [comment]
@iamturns can you please change this?

**Comment by iamturns** [comment]
The reason `@typescript-eslint/eslint-plugin` is a peer dependency, is because all ESLint plugins must be installed locally. This is a limitation within ESLint itself. See [RFC](https://github.com/eslint/rfcs/tree/master/designs/2019-config-simplification) and [progress](https://github.com/eslint/eslint/issues/13481)

To help with this, I've just removed the `peerDependency` (see #187). This allows more flexibility with the version of `eslint-plugin` you want to install. Also, the dependencies are unpinned, so that you can keep `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser` versions in sync too.

Hope this helps. Cheers!

**Comment by utrumo** [comment]
>  This issue has been resolved in version 12.0.1 
> 
> The release is available on:
> 
> * [npm package (@latest dist-tag)](https://www.npmjs.com/package/eslint-config-airbnb-typescript/v/12.0.1)
> * [GitHub release](https://github.com/iamturns/eslint-config-airbnb-typescript/releases/tag/v12.0.1)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot

@typescript-eslint/parser must also be removed from dependencies for keeping @typescript-eslint/eslint-plugin and @typescript-eslint/parser versions in sync too. This module is already in peer dependencies eslint-config-aribnb and eslint-config-airbinb-base
