### ISSUE TITLE
Add peerDependencies for eslint-config-airbnb-typescript

### ISSUE THREAD

**Issue by abcrun** [iamturns/eslint-config-airbnb-typescript#207]
Hi, 

Could you please add peerDependencies for `eslint-config-airbnb-typescript`?  For that I can get the peer dependencies through `npm info *** peerDependencies`

Thank you.

**Comment by eagerestwolf** [comment]
I agree with @abcrun, but for different reasons. When using yarn 2, yarn throws tons of warnings because `eslint-config-airbnb-typescript` doesn't provide the peer dependencies (which it shouldn't), but it ***should*** list the peer dependencies. I understand not wanting to do it because the peer dependencies vary between the main and base configs, not to mention npm and yarn (for now, that's coming in yarn 3) don't support conditional peer dependencies. However, the yarn developers have said that packages that do things like this will eventually be blocked from being installed entirely. I'm open to doing a PR if you want. It's literally a minor change to the `package.json`.


![Screen Shot 2021-06-03 at 6 32 13 AM](https://user-images.githubusercontent.com/3085408/120631235-a5dd8100-c435-11eb-9e05-9485259a1e62.png)

**Comment by jrolfs** [comment]
**13.0.0** fixed _most_ of the peer dependency warnings, but `eslint-config-airbnb-base` still wants `eslint` and `eslint-plugin-import` ... I think to properly address these last two we'd need to add them as `peerDependencies` of this package, right? Am I missing something here?

<img width="1584" alt="peer-deps" src="https://user-images.githubusercontent.com/288160/152615192-083dd84f-6c8c-4011-b832-c1c4e78cc02c.png">
